#web_controllers:
#    resource: ../../src/Controller/Web
#    type: annotation
#    prefix: '/'
#    name_prefix: 'web_'

rest_controllers:
    resource: ../../src/Controller/Rest
    type: annotation
    prefix: '/api'
    name_prefix: 'api_'

etst_controllers:
    resource: ../../src/Controller
    type: annotation

